### ISSUE TITLE
Gracefully shutting down JIRA om docker stop

### ISSUE THREAD

**Issue by ismarslomic** [cptactionhank/docker-atlassian-jira-software#11]
Hi,
Any thoughts about adding graceful shut down of JIRA on `docker stop`?

See this blog: https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/

**Comment by ismarslomic** [comment]
@cptactionhank would you be able to support me on how we could achieve this?

**Comment by cptactionhank** [comment]
Please not that it is not me that have developed the Atlassian products so I cannot do anything magical about this. 

When the container is shutdown i.e. `docker stop` the main process which is the a tomcat instance running in foreground, it receives the default `SIGTERM` (15) and begins to gracefully shutdown however the Tomcat and Atlassian application has implemented on how to. (Exit code is usually 143 because of the JVM)

If you are experiencing that the container is shutdown is with exit code SIGKILL (9 or 137) then you process has been to slow and Docker is killing it in a harsher way on your behalf. Please see the section "docker stop" in your provided link.

When shutting down my own containers with appropiate timeouts I get the Apache Tomcat Native statistics output in the end which to me indicated that the application has shut down gracefully. A hard shutdown like SIGKILL (9) I believe would not yield the APR statistics in the end.

**Comment by cptactionhank** [comment]
Closed since we're already utilizing Tomcat's normal shutdown procedure
