### ISSUE TITLE
7.3 to 7.4 doesn't trigger update state.

### ISSUE THREAD

**Issue by zyxep** [cptactionhank/docker-atlassian-jira-software#29]
Hi,

I have tried to update my container to the newest 7.4.0 image.
I have a postgres 9.5.7 in a network with jira & bitbucket.

I run this command to start my container:
`docker run --rm --network=atlassian -v jiraInstallVolume:/opt/atlassian/jira -v jiraVolume:/var/atlassian/jira --name="jira" -d -p 8080:8080 cptactionhank/atlassian-jira-software:7.4.0`

as you can see I have also 2 volumes, 1 for install dir & one for the data too.
I have these 2 so i can alter my server cfg to proxy to https.

I have a Nginx installed on the host which proxies to the jira container.

I ran the same command just with 7.3.7, and that is what my jira "think" it is running.

**Comment by zyxep** [comment]
Hey, any idea why it doesn't trigger an update?

**Comment by cptactionhank** [comment]
Yes, you mounted the installation directory of an older version replacing the installation directory of the newer installation.

Typically it is not needed to mount the installation directory.

Remove the /opt/atlassian mount and it should start up version 7.4.0.

**Comment by zyxep** [comment]
Then I don't understand how to tell server.xml that it's running behind a proxy, so I get SSL.

**Comment by cptactionhank** [comment]
There are environment variables to mitigate this scenario, have a look at 

#       "X_PROXY_NAME=localhost",
#       'X_PROXY_PORT=1234',
#       'X_PROXY_SCHEME=http',
#       'X_PATH=/jira-path'

You can see exactly what happends in docker-entrypoint.sh or you can mount your server.xml file instead of a whole directory. I would recommend the X_* environment variables.
